// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuMSV9vXX4lMu4HH9quGqJOFFEdOrbNTs',
    appId: '1:826723606162:web:0d35ff459c7b33a9dad04b',
    messagingSenderId: '826723606162',
    projectId: 'pspad-37883',
    authDomain: 'pspad-37883.firebaseapp.com',
    storageBucket: 'pspad-37883.firebasestorage.app',
    measurementId: 'G-VYBF8K8WEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHmstjO3QR86FSmDbESB5H6CwWb2U0p8',
    appId: '1:826723606162:android:459b5dcd0f6ad311dad04b',
    messagingSenderId: '826723606162',
    projectId: 'pspad-37883',
    storageBucket: 'pspad-37883.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxyBXtuvNVHak8kLqUw_C-0aPu7W680eU',
    appId: '1:826723606162:ios:08c707d2679bf68fdad04b',
    messagingSenderId: '826723606162',
    projectId: 'pspad-37883',
    storageBucket: 'pspad-37883.firebasestorage.app',
    iosBundleId: 'com.example.pspad',
  );
}
