// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNxFQS27hCV3GUT8sSOawFAz3KpHCFKWQ',
    appId: '1:346471625692:web:6f64b0adf40883bedf1519',
    messagingSenderId: '346471625692',
    projectId: 'examen2parte1-565e8',
    authDomain: 'examen2parte1-565e8.firebaseapp.com',
    storageBucket: 'examen2parte1-565e8.firebasestorage.app',
    measurementId: 'G-SXGSGGQFQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH69iFxqM2lvWLfZX8jhoflaYSxVU6Rss',
    appId: '1:346471625692:android:70c5d819b5b82bdddf1519',
    messagingSenderId: '346471625692',
    projectId: 'examen2parte1-565e8',
    storageBucket: 'examen2parte1-565e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMBgq8ETS1rPY66JQjfQAhBR8hFt-kx8',
    appId: '1:346471625692:ios:471c06048c5721d2df1519',
    messagingSenderId: '346471625692',
    projectId: 'examen2parte1-565e8',
    storageBucket: 'examen2parte1-565e8.firebasestorage.app',
    iosBundleId: 'com.example.examen2parte1',
  );
}
